# Generated by Django 4.2.8 on 2023-12-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditApp', '0003_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
