# Generated by Django 4.2.8 on 2023-12-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditApp', '0004_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayments_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
